image:
  file: .gitpod.Dockerfile

tasks:
  - name: Verify Tools
    init: aws --version && kubectl version --client && eksctl version
    command: echo "✅ All tools installed"

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
